/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package cron

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class CronExpressionBuilderTest {

    @Test
    fun `should convert tokenized string into cron expression`() {
        val tokenizedCronExpression = TokenizedCronExpression(
            "*/15", "0", "1,15", "*", "1-5", """echo "random text""""
        )
        val expected = CronExpression(
            setOf(0, 15, 30, 45),
            setOf(0),
            setOf(1, 15),
            setOf(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
            setOf(1, 2, 3, 4, 5),
            tokenizedCronExpression.command
        )

        val actual = CronExpressionBuilder.build(tokenizedCronExpression)

        assertEquals(expected, actual)
    }
}
